#coding:utf-8
import clc99
clc99.initsystem()
clc99.print_status('status')
clc99.print_good('ok!')
clc99.print_error('error!')
clc99.print_warning('warning!')
clc99.print_finish('finish')
clc99.print_os('os ok!')
clc99.print_notrun('This is a comment')
clc99.print_e('error!')
clc99.print_fileok('file ok!')
clc99.print_filerror('file error!')
clc99.print_time()
clc99.print_music('play 123.mp3')
clc99.print_video('play 1234.mp4')
clc99.print_ok('OK!')
clc99.print_over('system over;)')
clc99.print_admin('Successfully obtained administrator privileges!')
#clc99.input_str('input:')
print("'input_str'Parameters can return the user's input, which is not demonstrated here")
clc99.print_dirok('dirok')
clc99.print_direrror('direrror')
clc99.print_comok('The equipment is normal！')
clc99.print_comerror('equipment error！')
clc99.print_uquestion('Do you know Python？')
clc99.print_cquestion('There is a problem with the procedure！')
def zidingyicolor(str):
    user_c = clc99.user_color('[b]','YELLOW')
    print(user_c+str)
zidingyicolor('Custom symbols')