#coding:utf-8
import clc99
clc99.initsystem()
clc99.print_status('123')
clc99.print_good('good!')
clc99.print_error('错误!')
clc99.print_warning('警告!')
clc99.print_finish('完成')
clc99.print_os('os ok!')
clc99.print_notrun('这是注释')
clc99.print_e('error!')
clc99.print_fileok('文件 ok!')
clc99.print_filerror('文件 error!')
clc99.print_time()
clc99.print_music('播放123.mp3')
clc99.print_video('播放1234.mp4')
clc99.print_ok('OK!')
clc99.print_over('system over;)')
clc99.print_admin('成功获取到管理员权限！')
#clc99.input_str('input:')
print('input_str参数可以返回用户输入的东西，这里不在演示')
clc99.print_dirok('dirok')
clc99.print_direrror('direrror')
clc99.print_comok('设备正常！')
clc99.print_comerror('设备错误！')
clc99.print_uquestion('你知道python吗？')
clc99.print_cquestion('程序有问题！')
def zidingyicolor(str):
    user_c = clc99.user_color('[b]','YELLOW')
    print(user_c+str)
zidingyicolor('自定义的符号')
