#coding:utf-8
import colorconsole99
from colorconsole99 import *
colors.initsystem()
colors.print_status('status')
colors.print_good('ok!')
colors.print_error('error!')
colors.print_warning('warning!')
colors.print_finish('finish')
colors.print_os('os ok!')
colors.print_notrun('This is a comment')
colors.print_e('error!')
colors.print_fileok('file ok!')
colors.print_filerror('file error!')
colors.print_time()
colors.print_music('play 123.mp3')
colors.print_video('play 1234.mp4')
colors.print_ok('OK!')
colors.print_over('system over;)')
colors.print_admin('Successfully obtained administrator privileges!')
#colors.input_str('input:')
print("'input_str'Parameters can return the user's input, which is not demonstrated here")
colors.print_dirok('dirok')
colors.print_direrror('direrror')
colors.print_comok('The equipment is normal！')
colors.print_comerror('equipment error！')
colors.print_uquestion('Do you know Python？')
colors.print_cquestion('There is a problem with the procedure！')
def zidingyicolor(str):
    user_c = colors.user_color('[b]','YELLOW')
    print(user_c+str)
zidingyicolor('Custom symbols')