#coding:utf-8
import colorconsole99
from colorconsole99 import *
colors.initsystem()
colors.print_status('123')
colors.print_good('good!')
colors.print_error('错误!')
colors.print_warning('警告!')
colors.print_finish('完成')
colors.print_os('os ok!')
colors.print_notrun('这是注释')
colors.print_e('error!')
colors.print_fileok('文件 ok!')
colors.print_filerror('文件 error!')
colors.print_time()
colors.print_music('播放123.mp3')
colors.print_video('播放1234.mp4')
colors.print_ok('OK!')
colors.print_over('system over;)')
colors.print_admin('成功获取到管理员权限！')
#colors.input_str('input:')
print('input_str参数可以返回用户输入的东西，这里不在演示')
colors.print_dirok('dirok')
colors.print_direrror('direrror')
colors.print_comok('设备正常！')
colors.print_comerror('设备错误！')
colors.print_uquestion('你知道python吗？')
colors.print_cquestion('程序有问题！')
def zidingyicolor(str):
    user_c = colors.user_color('[b]','YELLOW')
    print(user_c+str)
zidingyicolor('自定义的符号')
