#coding:utf-8
import colorconsole99_noclass
from colorconsole99_noclass import *
initsystem()
print_status('status')
print_good('ok!')
print_error('error!')
print_warning('warning!')
print_finish('finish')
print_os('os ok!')
print_notrun('This is a comment')
print_e('error!')
print_fileok('file ok!')
print_filerror('file error!')
print_time()
print_music('play 123.mp3')
print_video('play 1234.mp4')
print_ok('OK!')
print_over('system over;)')
print_admin('Successfully obtained administrator privileges!')
#colors.input_str('input:')
print("'input_str'Parameters can return the user's input, which is not demonstrated here")
print_dirok('dirok')
print_direrror('direrror')
print_comok('The equipment is normal！')
print_comerror('equipment error！')
print_uquestion('Do you know Python？')
print_cquestion('There is a problem with the procedure！')
def zidingyicolor(str):
    user_c = user_color('[b]','YELLOW')
    print(user_c+str)
zidingyicolor('Custom symbols')