#coding:utf-8
import clc99
clc99.initsystem()
clc99.print_status('status',end="a")
clc99.print_good('ok!',end="a")
clc99.print_error('error!',end="a")
clc99.print_warning('warning!',end="a")
clc99.print_finish('finish',end="a")
clc99.print_os('os ok!',end="a")
clc99.print_notrun('This is a comment',end="a")
clc99.print_e('error!',end="a")
clc99.print_fileok('file ok!',end="a")
clc99.print_filerror('file error!',end="a")
clc99.print_time()
clc99.print_music('play 123.mp3',end="a")
clc99.print_video('play 1234.mp4',end="a")
clc99.print_ok('OK!',end="a")
clc99.print_over('system over;)',end="a")
clc99.print_admin('Successfully obtained administrator privileges!',end="a")
#clc99.input_str('input:',end="a")
print("'input_str'Parameters can return the user's input, which is not demonstrated here")
clc99.print_dirok('dirok',end="a")
clc99.print_direrror('direrror',end="a")
clc99.print_comok('The equipment is normal！',end="a")
clc99.print_comerror('equipment error！',end="a")
clc99.print_uquestion('Do you know Python？',end="a")
clc99.print_cquestion('There is a problem with the procedure！',end="a")
def zidingyicolor(str):
    user_c = clc99.user_color('[b]','YELLOW')
    print(user_c+str)
zidingyicolor('Custom symbols')